apiVersion: v1
kind: Service
metadata:
  name: mysamplewebapi-loadbalancer
spec:
  type: LoadBalancer    #use for loadbalancing
  selector:
      app: mysamplewebapi
  ports:
    - name: "80"
      port: 80
      targetPort: 80