apiVersion: v1
kind: Pod
metadata:
  name: mysamplewebapi
  labels:
    app: samplewebapi
    rel: stable
spec:
  containers:
  - name: mysamplewebapi
    image: samplewebapi:latest
    imagePullPolicy: IfNotPresent 
    ports:
    - containerPort: 80
  